const db = require('../config/connection');
const { Card } = require('../models');

const json = require('./WAR.json');
const WAR = json.data.cards;

db.once('open', async () => {
  await Card.deleteMany({});
  const rankDict = {
    "God-Eternal Oketra" : 264,
    "Liliana, Dreadhorde General": 263,
    "Ugin, the Ineffable": 262,
    "Ilharg, the Raze-Boar": 261,
    "God-Eternal Kefnet": 260,
    "Sarkhan the Masterless": 259,
    "God-Eternal Bontu": 258,
    "God-Eternal Rhonas": 257,
    "Gideon Blackblade": 256,
    "Finale of Eternity": 255,
    "Roalesk, Apex Hybrid": 254,
    "Finale of Glory": 253,
    "Massacre Girl": 252,
    "Enter the God-Eternals": 251,
    "Awakening of Vitu-Ghazi": 250,
    "Nissa, Who Shakes the World": 249,
    "Neheb, Dreadhorde Champion": 248,
    "Tolsimir, Friend to Wolves": 247,
    "Chandra, Fire Artisan": 246,
    "Dreadhorde Invasion": 245,
    "Nicol Bolas, Dragon-God": 244,
    "Time Wipe": 16,
    "Ajani, the Greathearted": 243,
    "Storrev, Devkarin Lich": 242,
    "Prison Realm": 241,
    "Feather, the Redeemed": 240,
    "Vivien, Champion of the Wilds": 239,
    "Angrath, Captain of Chaos": 238,
    "Vraska, Swarm's Eminence": 237,
    "Bioessence Hydra": 236,
    "Kasmina, Enigmatic Mentor": 235,
    "Widespread Brutality": 234,
    "Kaya, Bane of the Dead": 233,
    "Arlinn, Voice of the Pack": 232,
    "Ob Nixilis's Cruelty": 231,
    "Krenko, Tin Street Kingpin": 230,
    "Domri, Anarch of Bolas": 229,
    "Jaya's Greeting": 228,
    "Commence the Endgame": 227,
    "Sorin, Vengeful Bloodlord": 226,
    "Bleeding Edge": 225,
    "Eternal Skylord": 224,
    "Oath of Kaya": 223,
    "Nahiri, Storm of Stone": 222,
    "Ral, Storm Conduit": 221,
    "Living Twister": 220,
    "Ral's Outburst": 219,
    "Finale of Revelation": 218,
    "Rescuer Sphinx": 217,
    "Casualties of War": 216,
    "Jace, Wielder of Mysteries": 215,
    "Deathsprout": 214,
    "Band Together": 213,
    "Evolution Sage": 212,
    "Elite Guardmage": 211,
    "Domri's Ambush": 210,
    "Challenger Troll": 209,
    "Chandra's Triumph": 208,
    "Bloom Hulk": 207,
    "Despark": 206,
    "Soul Diviner": 205,
    "Eternal Taskmaster": 204,
    "Paradise Druid": 203,
    "The Wanderer": 202,
    "Gleaming Overseer": 201,
    "Trusted Pegasus": 200,
    "Grateful Apparition": 199,
    "Law-Rune Enforcer": 198,
    "Jaya, Venerated Firemage": 197,
    "Mizzium Tank": 196,
    "Merfolk Skydiver": 195,
    "Spark Harvest": 194,
    "Dreadhorde Twins": 193,
    "Vizier of the Scorpion": 192,
    "Aven Eternal": 191,
    "Solar Blaze": 190,
    "Ob Nixilis, the Hate-Twisted": 189,
    "Mobilized District": 188,
    "Tyrant's Scorn": 187,
    "Karn's Bastion": 186,
    "Saheeli, Sublime Artificer": 185,
    "Mowu, Loyal Companion": 184,
    "Tibalt, Rakish Instigator": 183,
    "Leyline Prowler": 182,
    "Jiang Yanggu, Wildcrafter": 181,
    "Tibalt's Rager": 180,
    "Planewide Celebration": 179,
    "Pollenbright Druid": 178,
    "Teferi, Time Raveler": 177,
    "Vivien's Arkbow": 176,
    "Wanderer's Strike": 175,
    "Divine Arrow": 174,
    "Spellgorger Weird": 173,
    "Spark Double": 172,
    "Davriel, Rogue Shadowmage": 171,
    "Tomik, Distinguished Advokist": 170,
    "Cyclops Electromancer": 169,
    "Thunder Drake": 168,
    "Sunblade Angel": 167,
    "Blast Zone": 166,
    "Huatli's Raptor": 165,
    "Kiora, Behemoth Beckoner": 164,
    "Raging Kronch": 163,
    "Vraska's Finisher": 162,
    "Lazotep Reaver": 161,
    "Dreadhorde Butcher": 160,
    "Ugin's Conjurant": 159,
    "Pledge of Unity": 158,
    "Tamiyo's Epiphany": 157,
    "Turret Ogre": 156,
    "Samut, Tyrant Smasher": 155,
    "Tenth District Legionnaire": 154,
    "Finale of Devastation": 153,
    "Ajani's Pridemate": 152,
    "Flux Channeler": 151,
    "Gideon's Triumph": 150,
    "Enforcer Griffin": 149,
    "Herald of the Dreadhorde": 148,
    "Arlinn's Wolf": 147,
    "The Elderspell": 146,
    "Callous Dismissal": 145,
    "Fblthp, the Lost": 144,
    "Dreadhorde Arcanist": 143,
    "Centaur Nurturer": 142,
    "Silent Submersible": 141,
    "Cruel Celebrant": 140,
    "Rubblebelt Rioters": 139,
    "Sorin's Thirst": 138,
    "Sky Theater Strix": 137,
    "Giant Growth": 136,
    "Dovin, Hand of Control": 135,
    "Augur of Bolas": 134,
    "Role Reversal": 133,
    "Dreadmalkin": 132,
    "Spellkeeper Weird": 131,
    "Finale of Promise": 130,
    "Chandra's Pyrohelix": 129,
    "Devouring Hellion": 128,
    "Parhelion II": 127,
    "Erratic Visionary": 126,
    "Burning Prophet": 125,
    "Martyr for the Cause": 124,
    "Thundering Ceratok": 123,
    "Kronch Wrangler": 122,
    "Ashiok, Dream Render": 121,
    "Snarespinner": 120,
    "Pouncing Lynx": 119,
    "Vivien's Grizzly": 118,
    "Shriekdiver": 117,
    "Spark Reaper": 116,
    "Mayhem Devil": 115,
    "War Screecher": 114,
    "Rising Populace": 113,
    "Jace's Triumph": 112,
    "Command the Dreadhorde": 111,
    "Liliana's Triumph": 110,
    "Price of Betrayal": 109,
    "Single Combat": 108,
    "Kasmina's Transmutation": 107,
    "Vampire Opportunist": 106,
    "Bolas's Citadel": 105,
    "Gateway Plaza": 104,
    "Ahn-Crop Invader": 103,
    "Interplanar Beacon": 102,
    "Aid the Fallen": 101,
    "Angrath's Rampage": 100,
    "No Escape": 99,
    "Narset, Parter of Veils": 98,
    "Heartfire": 97,
    "New Horizons": 96,
    "Bond of Discipline": 95,
    "Chainwhip Cyclops": 94,
    "Battlefield Promotion": 93,
    "Kraul Stinger": 92,
    "Tithebearer Giant": 91,
    "Bond of Flourishing": 90,
    "Guild Globe": 89,
    "Makeshift Battalion": 88,
    "Firemind Vessel": 87,
    "Narset's Reversal": 86,
    "Relentless Advance": 85,
    "Wardscale Crocodile": 84,
    "Tamiyo, Collector of Tales": 83,
    "Bond of Revival": 82,
    "Invading Manticore": 81,
    "Teyo's Lightshield": 80,
    "Saheeli's Silverwing": 79,
    "Contentious Plan": 78,
    "Unlikely Aid": 77,
    "Bond of Insight": 76,
    "Kiora's Dambreaker": 75,
    "Ashiok's Skulker": 74,
    "Lazotep Plating": 73,
    "Naga Eternal": 72,
    "Duskmantle Operative": 71,
    "Grim Initiate": 70,
    "Mana Geode": 69,
    "Iron Bully": 68,
    "Toll of the Invasion": 67,
    "Honor the God-Pharaoh": 66,
    "Stealth Mission": 65,
    "Ravnica at War": 64,
    "Loxodon Sergeant": 63,
    "Invade the City": 62,
    "Primordial Wurm": 61,
    "Lazotep Behemoth": 60,
    "Bolt Bend": 59,
    "Goblin Assault Team": 58,
    "Nissa's Triumph": 57,
    "Huatli, the Sun's Heart": 56,
    "Teferi's Time Twist": 55,
    "Niv-Mizzet Reborn": 54,
    "Deliver Unto Evil": 53,
    "Ironclad Krovod": 52,
    "Crush Dissent": 51,
    "Karn, the Great Creator": 50,
    "Teyo, the Shieldmage": 49,
    "Ignite the Beacon": 48,
    "Defiant Strike": 47,
    "Charity Extractor": 46,
    "Prismite": 45,
    "Samut's Sprint": 44,
    "Courage in Crisis": 43,
    "Bulwark Giant": 42,
    "Steady Aim": 41,
    "Bond of Passion": 40,
    "Goblin Assailant": 39,
    "Sarkhan's Catharsis": 38,
    "Blindblast": 37,
    "Totally Lost": 36,
    "God-Pharaoh's Statue": 35,
    "Storm the Citadel": 34,
    "Emergence Zone": 33,
    "Rally of Wings": 32,
    "Davriel's Shadowfugue": 31,
    "Forced Landing": 30,
    "Heartwarming Redemption": 29,
    "Topple the Statue": 28,
    "Nahiri's Stoneblades": 27,
    "Wall of Runes": 26,
    "Return to Nature": 25,
    "Charmed Stray": 24,
    "Dovin's Veto": 23,
    "Kaya's Ghostform": 22,
    "Gideon's Sacrifice": 21,
    "Arboreal Grazer": 20,
    "Banehound": 19,
    "Neoform": 18,
    "Demolish": 17,
  };

  let seedArray = [];
  WAR.forEach(card => {
    if (card.number.indexOf('★') != -1 || card.number.indexOf('-') != -1 || card.type.includes('Basic Land') || card.number > 264) {
      return;
    }
    const setNumber = card.number;
    const cardRank = rankDict[card.name];
    const manaCost = card.manaCost ? card.manaCost : "{0}";

    let tempCard = {
      "setNumber" : setNumber,
      "name" : card.name,
      "multiverseId" : card.identifiers.multiverseId,
      "rank": cardRank,
      "cmc": card.manaValue,
      "manaCost": manaCost,
      "colors": card.colors,
      "types": card.types
    }
    seedArray.push(tempCard);
  })

  await Card.create(seedArray);

  console.log('all done!');
  process.exit(0);
});
